blog/urls.py
from django.urls import path
from . import views

urlpatterns = [
    path('', views.post_list, name='post_list'),
    path('post/<int:pk>/', views.post_detail, name='post_detail'),
    path('post/new/', views.post_new, name='post_new'),
    path('post/<int:pk>/edit/', views.post_edit, name='post_edit'),
    path('post/<int:pk>/delete/', views.post_delete, name='post_delete'),
    path('post/<int:pk>/comment/', views.add_comment_to_post, name='add_comment_to_post'),
    path('toggle_favorite/<int:pk>/', views.toggle_favorite, name='toggle_favorite'),
]

mysite/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('blog.urls')),
]

blog/models.py
from django.conf import settings
from django.db import models
from django.utils import timezone
from django.contrib.auth.models import User
from django import forms


class Post(models.Model):
    author = models.ForeignKey(settings.AUTH_USER_MODEL, on_delete=models.CASCADE)
    title = models.CharField(max_length=200)
    text = models.TextField()
    favoritos = models.ManyToManyField(User, related_name='favoritos', blank=True)
    created_date = models.DateTimeField(
            default=timezone.now)
    published_date = models.DateTimeField(
            blank=True, null=True)

    def publish(self):
        self.published_date = timezone.now()
        self.save()

    def __str__(self):
        return self.title




class Comment(models.Model):
    post = models.ForeignKey('blog.Post', related_name='comments', on_delete=models.CASCADE)
    author = models.CharField(max_length=200)
    text = models.TextField()
    created_date = models.DateTimeField(default=timezone.now)

    def __str__(self):
        return self.text
    

blog/forms.py
from django import forms

from .models import Post

class PostForm(forms.ModelForm):

    class Meta:
        model = Post
        fields = ('title', 'text',)

blog/views.py
from django.shortcuts import render, get_object_or_404, redirect
from django.utils import timezone
from .models import Post, Comment
from .forms import PostForm
from django.http import JsonResponse
from django.contrib.auth.decorators import login_required





@login_required
def toggle_favorite(request, pk):
    post = get_object_or_404(Post, pk=pk)
    if request.method == 'POST':
        if request.user in post.favoritos.all():
            post.favoritos.remove(request.user)
            favorited = False
        else:
            post.favoritos.add(request.user)
            favorited = True
        post.save()
        return JsonResponse({'favorited': favorited})
    return JsonResponse({'error': 'Invalid request'})




def post_detail(request, pk):
    post = get_object_or_404(Post, pk=pk)
    comments = post.comments.all()
    return render(request, 'blog/post_detail.html', {'post': post, 'comments': comments})

def add_comment_to_post(request, pk):
    post = get_object_or_404(Post, pk=pk)
    if request.method == 'POST':
        author = request.POST['author']
        text = request.POST['text']
        Comment.objects.create(post=post, author=author, text=text)
        return redirect('post_detail', pk=post.pk)
    return render(request, 'blog/comments.html', {'post': post})

def post_delete(request, pk):
    post = get_object_or_404(Post, pk=pk)
    post.delete()
    return redirect('post_list')

def post_list(request):
    posts = Post.objects.filter(published_date__lte=timezone.now()).order_by('published_date')
    return render(request, 'blog/post_list.html', {'posts': posts})

def post_new(request):
    if request.method == "POST":
        form = PostForm(request.POST)
        if form.is_valid():
            post = form.save(commit=False)
            post.author = request.user
            post.published_date = timezone.now()
            post.save()
            return redirect('post_detail', pk=post.pk)
    else:
        form = PostForm()
    return render(request, 'blog/post_edit.html', {'form': form})

def post_edit(request, pk):
    post = get_object_or_404(Post, pk=pk)
    if request.method == "POST":
        form = PostForm(request.POST, instance=post)
        if form.is_valid():
            post = form.save(commit=False)
            post.author = request.user
            post.published_date = timezone.now()
            post.save()
            return redirect('post_detail', pk=post.pk)
    else:
        form = PostForm(instance=post)
    return render(request, 'blog/post_edit.html', {'form': form})

blog/templates/blog/base.html
{% load static %}
<html>
    <head>
        <title>Pablo App</title>
        <link rel="stylesheet" href="//maxcdn.bootstrapcdn.com/bootstrap/3.2.0/css/bootstrap.min.css">
        <link rel="stylesheet" href="//maxcdn.bootstrapcdn.com/bootstrap/3.2.0/css/bootstrap-theme.min.css">
        <link href='//fonts.googleapis.com/css?family=Lobster&subset=latin,latin-ext' rel='stylesheet' type='text/css'>
        <link rel="stylesheet" href="{% static 'css/blog.css' %}">
        <script src="https://code.jquery.com/jquery-3.7.1.min.js" integrity="sha256-/JqT3SQfawRcv/BIHPThkBvs0OEvtFFmqPF/lYI/Cxo=" crossorigin="anonymous"></script>
        <link rel="stylesheet" href="{% static 'css/js/votacion.js' %}">
    </head>
    <body >
        <form action="">
            {% csrf_token %}
        </form>
        
        <div class="page-header">
            {% if user.is_authenticated %}
            <a href="{% url 'post_new' %}" class="top-menu"><span class="glyphicon glyphicon-plus"></span></a>
            {% endif %}
            <img src="{% static 'css/img/icon.jpg' %}" alt="Descripción de la imagen" class="logo-img">
            <h1><a href="/">Forum Romanum</a></h1>
        </div>
        <div class="content container">
            <div class="row">
                <div class="col-md-8">
                    {% block content %}
                    {% endblock %}
                </div>
            </div>
        </div>
        <script>
$(document).ready(function() {

console.log("cargado");
$('.toggle-favorite').click(function(e) {
    e.preventDefault();
    var postId = $(this).data('post-id');
    var favorited = $(this).data('favorited');
    var csrfToken = $('input[name="csrfmiddlewaretoken"]').val();
    $.ajax({
        type: 'POST',
        url: '/toggle_favorite/' + postId + '/',
        data: {
            'csrfmiddlewaretoken': csrfToken, // Usar el token CSRF
        },
        success: function(data) {
            if (data.favorited) {
                $('.toggle-favorite[data-post-id="' + postId + '"]').text('Remove from Favorites');
            } else {
                $('.toggle-favorite[data-post-id="' + postId + '"]').text('Add to Favorites');
            }
        },
        error: function(xhr, textStatus, errorThrown) {
            console.log('Error:', errorThrown);
        }
    });
});
});
        </script>
    </body>
</html>

blog/templates/blog/comments.html
<h3>Comments</h3>
{% if comments %}
    {% for comment in comments %}
        <div class="comment">
            <p>{{ comment.author }} ({{ comment.created_date|date:"d/m/Y H:i" }})</p>
            <p>{{ comment.text }}</p>
        </div>
    {% endfor %}
{% else %}
    <p>No comments yet.</p>
{% endif %}

<hr>
<h3>Escribe un comentario</h3>
<form method="post" action="{% url 'add_comment_to_post' pk=post.pk %}">
    {% csrf_token %}
    <div class="form-group">
        <label for="id_author">Your name:</label>
        <input class="form-control" id="id_author" name="author" required>
    </div>
    <div class="form-group">
        <label for="id_text">Comment:</label>
        <textarea class="form-control" id="id_text" name="text" required></textarea>
    </div>
    <button type="submit" class="btn btn-primary">Submit</button>
</form>

blog/templates/blog/post_detail.html
{% extends 'blog/base.html' %}
{% block content %}
    <div class="post">
        {% if post.published_date %}
            <div class="date">
                {{ post.published_date }}
            </div>
        {% endif %}
        <a class="btn btn-default" href="{% url 'post_edit' pk=post.pk %}">
            <span class="glyphicon glyphicon-pencil"></span>
        </a>
        <h2>{{ post.title }}</h2>
        <p>{{ post.text|linebreaksbr }}</p>
       
    </div>
    <!-- Bloque de comentarios -->
    <div class="comments">
        <h3>Comments</h3>
        {% for comment in comments %}
            <div class="comment">
                <p>{{ comment.author }} ({{ comment.created_date }}): {{ comment.text }}</p>
            </div>
        {% empty %}
            <p>No comments yet.</p>
        {% endfor %}

        <!-- Formulario para agregar comentarios -->
        <h3>Add a comment</h3>
        <form method="post" action="{% url 'add_comment_to_post' pk=post.pk %}">
            {% csrf_token %}
            <div class="form-group">
                <label for="id_author">Your name:</label>
                <input class="form-control" id="id_author" name="author" required>
            </div>
            <div class="form-group">
                <label for="id_text">Comment:</label>
                <textarea class="form-control" id="id_text" name="text" required></textarea>
            </div>
            <button type="submit" class="btn btn-primary">Submit</button>
        </form>
    </div>
{% endblock %}

blog/templates/blog/post_edit.html
{% extends 'blog/base.html' %}

{% block content %}
    <h2>New post</h2>
    <form method="POST" class="post-form">{% csrf_token %}
        {{ form.as_p }}
        <button type="submit" class="save btn btn-secondary">Save</button>
    </form>
{% endblock %}

blog/templates/blog/post_list.html
{% extends 'blog/base.html' %}
{% block content %}
{% for post in posts %}
<div>
    <p> Publicado: {{ post.published_date }}</p>
    <h2><a href="{% url 'post_detail' pk=post.pk %}">{{ post.title }}</a></h2>
    <p>{{ post.text|linebreaksbr }}</p>
    {% if user.is_authenticated %}
    {% if user in post.favoritos.all %}
        <button class="btn btn-danger toggle-favorite" data-post-id="{{ post.pk }}" data-favorited="true">Remove from Favorites</button>
    {% else %}
        <button class="btn btn-primary toggle-favorite" data-post-id="{{ post.pk }}" data-favorited="false">Add to Favorites</button>
    {% endif %}
    {% endif %}
    <div class="btn-container">
        <form method="GET" action="{% url 'post_edit' pk=post.pk %}" style="display: inline;">
            <button type="submit" class="btn btn-roman">Editar</button>
        </form>
        <form method="POST" action="{% url 'post_delete' pk=post.pk %}">
            {% csrf_token %}
            <button type="submit" class="btn btn-roman">Eliminar</button>
        </form>
        
</div>
{% endfor %}
{% endblock %}